"""init schema

Revision ID: e547663ec010
Revises: 
Create Date: 2025-12-20 17:20:10.007044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e547663ec010'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('tracking_code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'IN_TRANSIT', 'ON_HOLD', 'DELIVERED', 'LOST', name='packagestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('package_id'),
    sa.UniqueConstraint('tracking_code'),
    sa.CheckConstraint('weight_kg > 0', name='ck_packages_weight_kg_positive')
    )
    op.create_index('ix_packages_last_scan_at', 'packages', ['last_scan_at'], unique=False)
    op.create_index('ix_packages_status_destination', 'packages', ['status', 'destination'], unique=False)
    op.create_table('scan_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.Enum('CHECKIN', 'CHECKOUT', 'CUSTOMS_HOLD', 'DELIVERED', 'LOST', name='eventtype'), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.package_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_scan_events_package_id_occurred_at', 'scan_events', ['package_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scan_events_package_id_occurred_at', table_name='scan_events')
    op.drop_table('scan_events')
    op.drop_index('ix_packages_status_destination', table_name='packages')
    op.drop_index('ix_packages_last_scan_at', table_name='packages')
    op.drop_table('packages')
    op.execute('DROP TYPE IF EXISTS packagestatus')
    op.execute('DROP TYPE IF EXISTS eventtype')
    # ### end Alembic commands ###
